name       : gom
version    : 0.3.2
release    : 4
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gom/0.3/gom-0.3.2.tar.xz : bce8f0f94af6ff7847b853580ba6baebbab8ae531cedb0c78a5c473f39c758fd
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GObject Data Mapper
description: |
    GObject Data Mapper
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gobject-2.0)
    - pkgconfig(sqlite3)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(pygobject-3.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
