name       : gom
version    : '0.4'
release    : 5
source     :
    - https://download.gnome.org/sources/gom/0.4/gom-0.4.tar.xz : 68d08006aaa3b58169ce7cf1839498f45686fba8115f09acecb89d77e1018a9d
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GObject Data Mapper
description: |
    GObject Data Mapper
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sqlite3)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
